version: "3.8"
services:
  ubuntu:
    build: .
    volumes:
      - ./files:/root/files
    #environment:
    #  - CF_AC=don.ling.lok@gmail.com
    #  - CF_ID=
    #  - CF_TOKEN=Bearer 
    env_file:
      - .env
